name: TinaCMS Preview

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.86.0"
      - name: Install Dependencies
        run: npm install
      - name: Build Hugo Site
        run: hugo --minify
      - name: Start Development Server
        env:
          REPO_FULL_NAME: ${{ secrets.REPO_FULL_NAME }}
          TINA_CLIENT_ID: ${{ secrets.TINA_CLIENT_ID }}
          TINA_CLIENT_SECRET: ${{ secrets.TINA_CLIENT_SECRET }}
        run: npm run develop
